### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by jamrute** [russell-stewart/enrichrAPI#4]
Thanks for developing this tool! I tried running it on a set of genes and got the following error. I get the same error when I repeat it using your sample data file (genes2.txt). Any help would be greatly appreciated!

```
Enriching module ChiR
Uploading data...
Data uploaded.
Searching KEGG_2016...
  Non-ascii characters detected. I'll fix it...
Traceback (most recent call last):
  File "/Users/jamrute/enrichrAPI/enrichrAPI.py", line 95, in parseResults
    fileBody += chunk
TypeError: can only concatenate str (not "bytes") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamrute/enrichrAPI/enrichrAPI.py", line 319, in <module>
    parseResults(response , geneSetLibrary , entries)
  File "/Users/jamrute/enrichrAPI/enrichrAPI.py", line 100, in parseResults
    if ord(char) > 127:
TypeError: ord() expected string of length 1, but int found

```

**Comment by jamrute** [comment]
It was a Python2 vs 3 issue - sorted out.
